language: java
sudo: false

os: linux
dist: bionic
jdk: openjdk11

cache:
  directories:
    - $HOME/.m2

services:
  - xvfb

addons:
  apt:
    packages:
      - at-spi2-core
      - build-essential
      - libgtk-3-dev
      - libxtst-dev

before_script:
  - mkdir -p $HOME/graalvm && cd $HOME/graalvm
  - wget https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-19.3.0/graalvm-ce-java11-linux-amd64-19.3.0.tar.gz
  - tar xf graalvm-ce-java11-linux-amd64-19.3.0.tar.gz && cd $TRAVIS_BUILD_DIR
  - export GRAALVM_HOME=$HOME/graalvm/graalvm-ce-java11-19.3.0
  - ${GRAALVM_HOME}/bin/gu install native-image
  - echo $JAVA_OPTS

install: true

script:
  - mvn clean install
  - mvn client:build -pl App